version: "3.9"
services:
  psql:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./house_prices.csv:/house_prices.csv
    environment:
      - POSTGRES_USER=arantipov
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - spark-network

  spark-master:
    image: bitnami/spark:3
    depends_on:
      - psql       
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE = master
    volumes:
      - ./my_spark.py:/my_spark.py
    networks:
      - spark-network
  spark-worker-1:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network
  spark-worker-2:
      image: bitnami/spark:3
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      networks:
        - spark-network
networks:
  spark-network:
    driver: bridge