version: "3.9"
services:
  psql:
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./house_prices.csv:/house_prices.csv
    environment:
      - POSTGRES_USER=arantipov
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    networks:
      - spark-network
  spark-master:
    image: bitnami/spark:latest
    depends_on:
      - psql       
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE = master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./my_spark.py:/my_spark.py
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master  
    volumes:
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-2:
      image: bitnami/spark:latest
      command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077  
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      depends_on:
        - spark-master    
      volumes:
        - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar  
      networks:
        - spark-network
networks:
  spark-network:
    driver: bridge